name: Create FSH from ATT&CK Data
on: 
  push:
    branches: [ dev ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install mitreattack-python 

    - name: Run the script to create mitre attack tactics and (sub)techniques data structure 
      run: | 
        python scripts/create_tactics_and_techniques.py  

    - name: Run the script to create FSH files from the tactics and techniques data structure 
      run: |
        python scripts/create_fsh.py

    - name: Upload FSH files as artifact 
      uses: actions/upload-artifact@v4
      with: 
        name: fsh-files 
        path: |
          scripts/MITRE_FSH/*.fsh
