name: PublishIG

on:
  push: 
    branches: [main]
  #release:
  #  types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the implementation guide
      uses: actions/checkout@v2
      with:
        repository: constir1/ATTCK2FHIR
        path: .

    - name: Extract branch name
      run: |
        if ["${{ github.event.pull_request.head.ref }}" == ""]; then
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        else
          echo "##[set-output name=branch;]$(echo ${{ github.event.pull_request.head.ref }})"
        fi
      id: extract_branch
