name: Sushi Init

on: 
  pull_request:
    branches: [ dev ]

jobs:
  create_fsh:
    uses: constir1/ATTCK2FHIR/.github/workflows/create_fsh.yml@dev

  sushi_init:
    runs-on: ubuntu-latest
    needs: create_fsh  

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download FSH artifact
        uses: actions/download-artifact@v4
        with:
          name: fsh-files
          path: scripts/MITRE_FSH

      - name: Copy FSH files to IG directories
        run: bash scripts/move_fsh.sh
      

      